[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev"
]

[phases.build]
cmds = [
  "npm --prefix client run build",
  "npx prisma generate --schema=server/prisma/schema.prisma",
  "npm --prefix server run build"
]

[start]
cmd = "node server/dist/index.js"