[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm --prefix client run build",
  "npm --prefix server run db:generate",
  "npm --prefix server run build"
]

[start]
cmd = "npx prisma migrate deploy --schema server/prisma/schema.prisma && node server/dist/index.js"
